name: CILint

on:
  - push
  - pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Check environment
        run: |
          node --version
          npx eslint --version
      - name: Run ESLint
        run: npx eslint . --ext .js

