name: CILint

on:
  - push
  - pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Check environment
        run: |
          node --version
          npm --version
          npx eslint --version
      - name: Run ESLint
        run: npm test

